name: docs-deploy

on:
  push:
    branches:
      - main
      - ww/ci-doc-builds

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2

      - name: deps
        run: make dev

      - name: docs
        run: |
          make doc
          mv ./html/pip_audit /tmp/pip_audit

      - name: deploy
        run: |
          git config --global user.name 'woodruffw'
          git config --global user.email 'woodruffw@users.noreply.github.com'
          git checkout -b gh-pages
          mv /tmp/pip_audit ./docs
          git add ./docs
          git commit --amend -m "[docs] deploy: ${GITHUB_SHA}"
          git push --force origin gh-pages

      # - name: deploy
      #   uses: peaceiris/actions-gh-pages@v3.8.0
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./html/pip_audit
      #     publish_branch: gh-pages
      #     force_orphan: true
